project:
    name: testmilltest
    language: maven
applications:
-   name: platformtest
    vms:
    - name: ubuntu1204
    - name: centos6
      execute: true
    - name: fedora16
    - name: fedora17
